node {
    stage('cp') {
        sh 'cp -r /var/jenkins_home/daex-meta/* .'
    }
    
    stage('build gitlab') {
        dir('stacks') {
            sh './build_image.py docker.service:5000/daex-meta/gitlab gitlab/'
        }
    }
    
    stage('push gitlab') {
        dir('stacks') {
            sh './push_image.py docker.service:5000/daex-meta/gitlab'
        }
    }
    
    stage('deploy gitlab') {
        dir('stacks') {
             sh './deploy_stack.py gitlab gitlab/docker-compose.yml'
       }
    }
}
