node {
    withCredentials([
        string(credentialsId: 'port_user', variable: 'PORT_USER')
        ,string(credentialsId: 'port_pass', variable: 'PORT_PASS')
    ]) {

    	stage('Cloning daex-meta') {
        	git url: 'http://gitlab/daex/daex-meta.git'
    	}
    
    	stage('pull redis') {
            dir('stacks') {
        	sh 'docker pull redis:latest'
                sh 'docker tag redis:latest docker.service:5000/redis'
            }
        }
    
        stage('push redis') {
            dir('stacks') {
                sh 'docker push docker.service:5000/redis:latest'
            }
        }

        stage('build rqdash') {
            dir('stacks/redis') {
                sh 'docker build -t docker.service:5000/daex-meta/rqdash .'
            }
        }
    
        stage('push rqdash') {
            dir('stacks') {
                sh 'docker push docker.service:5000/daex-meta/rqdash:latest'
            }
        }
    
        stage('deploy redis') {
            dir('stacks') {
                sh 'deploy_stack redis redis/docker-compose.yml'
            }
        }
        
	stage('Update nginx') {
            dir('stacks') {
                sh 'add_folder nginx_nginx /etc/nginx/conf.d redis/rqdash.conf'
		sh 'redeploy_stack nginx nginx/docker-compose.yml'
            }
        }

    }
}
