node {
    withCredentials([
        string(credentialsId: 'port_user', variable: 'PORT_USER')
        ,string(credentialsId: 'port_pass', variable: 'PORT_PASS')
    ]) {

    	stage('Cloning daex-meta') {
        	git url: 'http://gitlab/daex/daex-meta.git'
    	}
    
    	stage('Build nginx') {
            dir('stacks/nginx') {
        	sh 'docker build -t docker.service:5000/daex-meta/nginx .'
            }
        }
    
        stage('Push nginx') {
            dir('stacks') {
                sh 'docker push docker.service:5000/nginx:latest'
            }
        }

        stage('Deploy nginx') {
            dir('stacks') {
                sh 'deploy_stack nginx nginx/docker-compose.yml'
            }
        }
        
	stage('Update nginx') {
            dir('stacks') {
                sh 'add_folder nginx_nginx /etc/nginx nginx/nginx/'
                sh 'add_folder nginx_nginx /usr/share/nginx/html nginx/html/'
		sh 'redeploy_stack nginx nginx/docker-compose.yml'
            }
        }

    }
}
