version: '3.2'
services:
  agent:
    image: docker.service:5000/portainer/agent
    environment:
      # REQUIRED: Should be equal to the service name prefixed by "tasks." when
      # deployed inside an overlay network
      AGENT_CLUSTER_ADDR: tasks.agent
      # AGENT_PORT: 9001
      # LOG_LEVEL: debug
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - docproc2
    deploy:
      mode: global
      placement:
        constraints: [node.platform.os == linux]
  portainer:
    image: docker.service:5000/portainer/portainer
    command: -H tcp://tasks.agent:9001 --tlsskipverify
    volumes:
      - data:/data
    networks:
      - docproc2
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
    extra_hosts:
      - "docker.service:192.168.1.64"
    ports:
      - 9000:9000 
volumes:
  data:      
networks:
  docproc2:
    external: true
